
- name: Deploy HTML code on Apache2 server
  hosts: localhost
  become: true
  become_user: root
  tasks:
  - name: Update apt-get repo
    command: apt-get update
  - name: Install Apache package on the server
    package: name=apache2 state=present
  - name: Start apache2 server
    service: name=apache2 state=started
  - name: Copy HTML code onto the apache2 server
    copy: src=index.html  dest=/var/www/html
    notify: Restart apache server

  handlers: 
  - name: Restart apache2 server
    service: name=apache2 state=restarted
